"""Offline pre-training from the closed-trade log (2026-09-05).

Why this exists
---------------
The deployed policy answers `skip` to essentially every open decision, which is a structural
deadlock rather than a bug: an undertrained policy declines every signal, so no trade opens, so no
reward arrives, so the weights never change (CLAUDE.md §16.9 documents this exact trap). Live
learning alone cannot escape it at this project's trade volume — `learner.py` performs roughly one
gradient step per closed trade, so reaching a useful number of updates would take a year of live
trading.

What this does
--------------
Replays the trades that ALREADY closed — every `paper_orders` row carries the exact observation
sent at decision time (`features_json`) plus its realized outcome — into the model's replay buffer,
then runs many gradient steps over that pooled experience. This is ordinary off-policy learning,
not a new mechanism: it is the same `replay_buffer.add()` + `model.train()` pair `learner.py`
already uses on every close, just applied in bulk to history instead of one trade at a time.

SAC is off-policy, which is what makes this valid: it can learn from experience generated by some
other policy (here, the strategy layer's own fixed-size decisions). This was one of the stated
reasons for moving off PPO (CLAUDE.md §15.11) — PPO could not use this data at all.

What this is NOT
----------------
Not a performance claim, and not `train.py --warm-start`. That path replays historical CANDLES and
lets the model trade them on-policy in a simulator; it was set aside (CLAUDE.md §15.8) after
diverging on data with no real strategy signals. This script never simulates anything — every
transition here is a real trade that really happened, with the real observation the model really
saw and the PnL it really produced.

Honest limits
-------------
- The actions in this data are not the model's own. Every trade was opened by the strategy layer at
  fixed size/leverage (rl_sizing has been off), so the action column has very little variance. The
  model learns "this market state, traded this way, produced this outcome" — good for valuing a
  situation, weak for learning to size, because it never sees what a different size would have done.
- ~730 distinct trades is small for RL. Past a few tens of thousands of gradient steps the model
  starts memorising these specific trades rather than generalising; `--gradient-steps` defaults
  accordingly and `--holdout` exists to make that visible rather than assumed.

Usage
-----
    python -m rl_service.pretrain --dsn postgres://... --model-in models/sac_global.zip \
        --buffer-in models/sac_global_buffer.pkl --model-out models/sac_pretrained.zip \
        --buffer-out models/sac_pretrained_buffer.pkl

Always writes to NEW output paths: the input model stays untouched so the two can be compared and
the original restored if this makes things worse.
"""
from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass
from typing import Any, Iterator, Optional

import numpy as np
from stable_baselines3 import SAC

from rl_service.learner import reward_from_outcome
from rl_service.obs import (
    ACTION_DIM,
    ACTIONS,
    MAX_SLTP_OFFSET_PCT,
    OBSERVATION_SCHEMA_VERSION,
    Observation,
    to_vector,
)


@dataclass
class Trade:
    """One closed trade, as far as offline learning is concerned."""

    order_id: int
    obs: Observation
    entry_px: float
    sl_px: Optional[float]
    tp_px: Optional[float]
    close_px: Optional[float]
    size_usd: float
    leverage: float
    realized_pnl: float
    close_reason: str


# Closes that represent a decision the POLICY made or lived with. A manual close is an operator
# action and a timeout is housekeeping; attributing either to the policy would train it on a
# decision it never made (the same reasoning CLAUDE.md §15.12 applies to terminal reward calls).
TRAINABLE_CLOSE_REASONS = {"sl", "tp", "rl_early"}

# Observation schema versions this script can read. v7 only APPENDED two fields to v6
# (max_position_pct, max_leverage — the risk budget), leaving every existing field at the same
# meaning and position, so a v6 row can be read as v7 by supplying those two values. That is the
# only reason upgrading is safe here: a version change that reordered, removed, or redefined a
# field could not be handled this way, and silently coercing one would misalign the vector exactly
# as CLAUDE.md §15.3's versioning exists to prevent. Widen this set only after checking the same
# holds for the version being added.
UPGRADABLE_SCHEMA_VERSIONS = {6, 7}


def upgrade_observation(payload: dict, from_version: int) -> dict:
    """Brings an older recorded observation up to the current schema.

    v6 -> v7: stamp the risk budget the trade was actually taken under. Every historical row comes
    from the fixed-sizing path, which sizes at equity/ActiveTokenCount (PaperTrader.dynamicNotional)
    — so the budget for those trades is that even share, not a config constant. augment.py restates
    the same value on every row it emits; this is what makes the untouched originals agree with it.
    """
    if from_version == OBSERVATION_SCHEMA_VERSION:
        return payload
    out = dict(payload)
    out["schema_version"] = OBSERVATION_SCHEMA_VERSION
    out.setdefault("max_position_pct", DEFAULT_MAX_POSITION_PCT)
    out.setdefault("max_leverage", DEFAULT_MAX_LEVERAGE)
    return out


# The budget historical trades were actually taken under: 10 active tokens sharing one account
# (CLAUDE.md §26's roster), and the exchange's 10x cap on this account.
DEFAULT_MAX_POSITION_PCT = 0.10
DEFAULT_MAX_LEVERAGE = 10.0


def load_trades(conn, *, limit: int = 0, min_id: int = 0) -> list[Trade]:
    """Reads closed trades with a usable decision-time observation.

    Rows whose features_json is missing, unparseable, or from a different observation schema are
    skipped rather than coerced: a vector built from a different layout would be silently
    misaligned, which corrupts training invisibly (CLAUDE.md §15.3's whole reason for versioning).
    """
    q = """
        SELECT id, features_json, entry_px, sl_px, tp_px, close_px, size, leverage,
               realized_pnl, close_reason
        FROM paper_orders
        WHERE closed_at IS NOT NULL
          AND features_json IS NOT NULL
          AND realized_pnl IS NOT NULL
          AND id > %s
        ORDER BY closed_at
    """
    params: list[Any] = [min_id]
    if limit > 0:
        q += " LIMIT %s"
        params.append(limit)

    out: list[Trade] = []
    skipped_schema = 0
    skipped_parse = 0
    skipped_reason = 0
    upgraded = 0

    with conn.cursor() as cur:
        cur.execute(q, params)
        for row in cur.fetchall():
            (order_id, features, entry_px, sl_px, tp_px, close_px, size,
             leverage, pnl, reason) = row

            if reason not in TRAINABLE_CLOSE_REASONS:
                skipped_reason += 1
                continue

            payload = features if isinstance(features, dict) else json.loads(features)
            version = int(payload.get("schema_version", -1))
            if version not in UPGRADABLE_SCHEMA_VERSIONS:
                skipped_schema += 1
                continue
            if version != OBSERVATION_SCHEMA_VERSION:
                payload = upgrade_observation(payload, version)
                upgraded += 1
            try:
                obs = Observation.model_validate(payload)
            except Exception:
                skipped_parse += 1
                continue

            out.append(
                Trade(
                    order_id=int(order_id),
                    obs=obs,
                    entry_px=_f(entry_px),
                    sl_px=_f(sl_px) or None,
                    tp_px=_f(tp_px) or None,
                    close_px=_f(close_px) or None,
                    size_usd=_f(size),
                    leverage=_f(leverage) or 1.0,
                    realized_pnl=_f(pnl),
                    close_reason=str(reason),
                )
            )

    if skipped_reason or skipped_schema or skipped_parse:
        print(
            f"skipped {skipped_reason} non-policy closes (manual/timeout), "
            f"{skipped_schema} schema mismatches, {skipped_parse} unparseable"
        )
    if upgraded:
        print(f"upgraded {upgraded} rows to observation schema v{OBSERVATION_SCHEMA_VERSION}")
    return out


def _f(v: Any) -> float:
    """Postgres NUMERIC arrives as Decimal; None becomes 0.0."""
    return 0.0 if v is None else float(v)


def action_vector(t: Trade) -> np.ndarray:
    """Reconstructs the action vector the trade's parameters correspond to.

    The action actually taken was never stored — `features_json` holds the observation only — so it
    is rebuilt from what the order itself records: its levels, size and leverage. This is faithful
    for these rows precisely BECAUSE the model did not choose them: with rl_sizing off, every trade
    used the strategy's levels at fixed sizing, so the order row IS the action that was taken.

    Layout mirrors decode_action (CLAUDE.md §15.11) exactly, in the policy's own [-1, 1] space:
      [0] sl offset from entry, scaled by MAX_SLTP_OFFSET_PCT
      [1] tp offset likewise
      [2] size_pct     — fraction of account equity committed
      [3] leverage_frac
      [4:] one-hot over ACTIONS

    Getting this layout wrong would teach the model to associate outcomes with actions nobody took,
    which is worse than not training at all — hence deriving it from the shared constants rather
    than hardcoding indices.
    """
    vec = np.zeros(ACTION_DIM, dtype=np.float32)

    if t.entry_px > 0:
        if t.sl_px:
            vec[0] = np.clip(((t.sl_px / t.entry_px) - 1.0) / MAX_SLTP_OFFSET_PCT, -1.0, 1.0)
        if t.tp_px:
            vec[1] = np.clip(((t.tp_px / t.entry_px) - 1.0) / MAX_SLTP_OFFSET_PCT, -1.0, 1.0)

    # size_pct is a fraction OF THE BUDGET under observation schema v7, not of the whole account —
    # decode_action multiplies it back by obs.max_position_pct, so encoding it against equity here
    # would train the model on actions that decode to something else entirely. Divide by the same
    # budget the observation carries.
    equity = float(t.obs.account_equity_usd or 0.0)
    budget_pct = float(t.obs.max_position_pct or 0.0)
    budget_usd = equity * budget_pct
    vec[2] = np.clip(t.size_usd / budget_usd, 0.0, 1.0) if budget_usd > 0 else 0.0

    # leverage_frac maps onto [1x, max_leverage]; invert against the observation's OWN ceiling
    # rather than a constant, so a row recorded under a different cap still round-trips correctly.
    max_leverage = float(t.obs.max_leverage or 10.0)
    if max_leverage > 1.0:
        vec[3] = np.clip((t.leverage - 1.0) / (max_leverage - 1.0), 0.0, 1.0)

    # These rows are all opens that ran to a close, so the action head is "open" — except an
    # rl_early close, which the model itself chose mid-trade.
    head = "close" if t.close_reason == "rl_early" else "open"
    if head in ACTIONS:
        vec[4 + ACTIONS.index(head)] = 1.0
    return vec


def terminal_observation(t: Trade, obs_dim: int) -> np.ndarray:
    """The observation as of the close, used as the transition's next_obs.

    Built from the decision-time observation with the price moved to the close and the position
    marked flat with its realized PnL attached — the same shape `lifecycle.go`'s terminal report
    sends. It is only ever bootstrapped through a `done=True` transition, so its exact contents
    matter far less than its shape, but keeping it honest costs nothing.
    """
    final = t.obs.model_copy(deep=True)
    if t.close_px:
        final.last_price = t.close_px
    if final.position_state is not None:
        final.position_state.position_open = False
        final.position_state.realized_pnl_usd = t.realized_pnl
    final.category = {
        "sl": "closed_sl",
        "tp": "closed_tp",
        "rl_early": "closed_early",
    }.get(t.close_reason, "closed_early")
    return to_vector(final, obs_dim)


def fill_buffer(model: SAC, trades: list[Trade], *, verbose: bool = True) -> int:
    """Adds each trade to the replay buffer as one terminal transition.

    done=True throughout: a closed trade has no successor state, and bootstrapping a future value
    off one would credit the policy for a position that no longer exists (same reasoning as
    learner.complete).
    """
    obs_dim = model.observation_space.shape[0]
    added = 0
    rewards: list[float] = []

    for t in trades:
        initial = float(t.obs.account_initial_usd or 0.0)
        reward = reward_from_outcome(t.realized_pnl, initial)
        try:
            obs_vec = to_vector(t.obs, obs_dim)
            next_vec = terminal_observation(t, obs_dim)
        except Exception as exc:  # a single malformed row must not abort the run
            if verbose:
                print(f"  order {t.order_id}: skipped ({exc})")
            continue

        model.replay_buffer.add(
            obs=obs_vec.reshape(1, -1),
            next_obs=next_vec.reshape(1, -1),
            action=action_vector(t).reshape(1, -1),
            reward=np.array([reward], dtype=np.float32),
            done=np.array([True]),
            infos=[{}],
        )
        rewards.append(reward)
        added += 1

    if verbose and rewards:
        arr = np.array(rewards)
        print(
            f"added {added} transitions | reward mean {arr.mean():+.5f} "
            f"min {arr.min():+.5f} max {arr.max():+.5f} | "
            f"wins {int((arr > 0).sum())} losses {int((arr < 0).sum())}"
        )
    return added


def evaluate(model: SAC, trades: list[Trade]) -> dict[str, float]:
    """Reports how the current policy answers the open decision on a set of trades.

    Deliberately NOT a profitability estimate — that would need a simulator and would be a
    performance claim this data cannot support. It answers one narrow, checkable question: does the
    policy still say `skip` to everything? That is the failure this whole exercise exists to escape,
    so it is the thing worth measuring before and after.
    """
    from rl_service.obs import decode_action

    obs_dim = model.observation_space.shape[0]
    counts: dict[str, int] = {}
    sizes: list[float] = []
    levs: list[float] = []

    for t in trades:
        probe = t.obs.model_copy(deep=True)
        # Ask the open question specifically, whatever category the row was recorded under.
        probe.category = "buy" if (probe.signal and probe.signal.side == "buy") else "sell"
        try:
            raw, _ = model.predict(to_vector(probe, obs_dim), deterministic=True)
            act = decode_action(raw, probe)
        except Exception:
            continue
        counts[act.action] = counts.get(act.action, 0) + 1
        sizes.append(act.size_pct)
        levs.append(act.leverage_frac)

    total = sum(counts.values()) or 1
    out = {f"pct_{k}": 100.0 * v / total for k, v in counts.items()}
    out["mean_size_pct"] = float(np.mean(sizes)) if sizes else 0.0
    # leverage_frac is [0,1] mapped onto [1x, max_leverage]; report the multiplier too, since a
    # bare fraction hides what it actually means at the configured 10x ceiling (CLAUDE.md §26).
    out["mean_lev_frac"] = float(np.mean(levs)) if levs else 0.0
    out["mean_lev_x"] = 1.0 + out["mean_lev_frac"] * 9.0
    out["n"] = float(total)
    return out


def _fmt(d: dict[str, float]) -> str:
    parts = [f"n={int(d.get('n', 0))}"]
    for k in sorted(d):
        if k.startswith("pct_"):
            parts.append(f"{k[4:]}={d[k]:.1f}%")
    parts.append(f"mean_size={d.get('mean_size_pct', 0):.4f}")
    parts.append(f"mean_lev={d.get('mean_lev_x', 0):.2f}x")
    return "  ".join(parts)


def main() -> None:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--dsn", default=os.environ.get("POSTGRES_DSN"), help="Postgres DSN")
    p.add_argument("--model-in", required=True)
    p.add_argument("--buffer-in", default="")
    p.add_argument("--model-out", required=True)
    p.add_argument("--buffer-out", default="")
    p.add_argument(
        "--gradient-steps",
        type=int,
        default=20000,
        help="Gradient steps to run. ~730 trades memorise past a few tens of thousands; "
        "20k is a deliberately conservative default.",
    )
    p.add_argument("--batch-size", type=int, default=0, help="0 = the model's own batch_size")
    p.add_argument(
        "--holdout",
        type=int,
        default=100,
        help="Most recent N trades withheld from training, used only to report before/after "
        "behaviour on data the model did not just fit. 0 disables.",
    )
    p.add_argument("--report-every", type=int, default=2000)
    p.add_argument("--limit", type=int, default=0)
    p.add_argument("--dry-run", action="store_true", help="Load and report, but do not train")
    p.add_argument(
        "--augment",
        type=int,
        default=0,
        help="Re-derive each trade at N additional (size, leverage) settings (see augment.py). "
        "0 disables. The recorded data has almost no action variance — 82%% of trades share one "
        "leverage — which is why the un-augmented run's requested size grew without bound.",
    )
    p.add_argument("--augment-seed", type=int, default=7)
    args = p.parse_args()

    if not args.dsn:
        p.error("--dsn or POSTGRES_DSN is required")
    if os.path.abspath(args.model_in) == os.path.abspath(args.model_out):
        p.error("--model-out must differ from --model-in: keep the original for comparison")

    from rl_service.data.postgres import connect

    print(f"loading model {args.model_in}")
    model = SAC.load(args.model_in)
    if args.buffer_in and os.path.exists(args.buffer_in):
        model.load_replay_buffer(args.buffer_in)
        print(f"loaded buffer: {model.replay_buffer.size()} existing transitions")

    # train() writes metrics; without a logger SB3 raises on the first write and the failure is easy
    # to miss (the exact silent-failure CLAUDE.md §15.11 records finding in the serving path).
    if getattr(model, "_logger", None) is None:
        from stable_baselines3.common.logger import configure

        model.set_logger(configure(folder=None, format_strings=[]))

    print("loading closed trades from Postgres")
    conn = connect(args.dsn)
    try:
        trades = load_trades(conn, limit=args.limit)
    finally:
        conn.close()
    print(f"{len(trades)} trainable closed trades")
    if not trades:
        print("nothing to train on")
        return

    holdout: list[Trade] = []
    if args.holdout > 0 and len(trades) > args.holdout * 2:
        holdout = trades[-args.holdout :]
        trades = trades[: -args.holdout]
        print(f"holding out the most recent {len(holdout)} trades; training on {len(trades)}")

    before_train = evaluate(model, trades[: min(200, len(trades))])
    before_hold = evaluate(model, holdout) if holdout else {}
    print(f"\nBEFORE  train: {_fmt(before_train)}")
    if holdout:
        print(f"BEFORE  holdout: {_fmt(before_hold)}")

    # Evaluation always uses the REAL trades — augmentation expands what the model learns from, not
    # what it is judged on. Augmenting the holdout would let rescaled copies of trades the model
    # trained on leak into the measurement and make it look better than it is.
    eval_trades = trades[: min(200, len(trades))]

    if args.augment > 0:
        from rl_service.augment import augment as augment_trades

        trades, astats = augment_trades(
            trades, variants=args.augment, seed=args.augment_seed
        )
        print(f"augmentation: {astats.summary()}")

    added = fill_buffer(model, trades)
    print(f"buffer now holds {model.replay_buffer.size()} transitions")

    if args.dry_run:
        print("\n--dry-run: stopping before training")
        return
    if added == 0:
        print("no transitions added; refusing to train")
        return

    batch = args.batch_size or model.batch_size
    print(f"\ntraining {args.gradient_steps} steps (batch {batch})")
    done = 0
    while done < args.gradient_steps:
        chunk = min(args.report_every, args.gradient_steps - done)
        model.train(gradient_steps=chunk, batch_size=batch)
        done += chunk
        line = f"  {done}/{args.gradient_steps}  train: {_fmt(evaluate(model, eval_trades))}"
        if holdout:
            line += f"\n            holdout: {_fmt(evaluate(model, holdout))}"
        print(line)

    print(f"\nAFTER   train: {_fmt(evaluate(model, eval_trades))}")
    if holdout:
        print(f"AFTER   holdout: {_fmt(evaluate(model, holdout))}")

    os.makedirs(os.path.dirname(args.model_out) or ".", exist_ok=True)
    model.save(args.model_out)
    print(f"\nsaved model to {args.model_out}")
    if args.buffer_out:
        os.makedirs(os.path.dirname(args.buffer_out) or ".", exist_ok=True)
        model.save_replay_buffer(args.buffer_out)
        print(f"saved buffer to {args.buffer_out}")
    print("\nthe input model is unchanged; compare the two before deploying either")


if __name__ == "__main__":
    main()
