"""Train a fresh SAC policy from the backtest's warm-start dataset.

This is the consumer of `cmd/backtest`'s JSONL output, and the step that breaks CLAUDE.md §16.9's
structural deadlock: a randomly initialised policy skips everything, so nothing opens, so nothing
closes, so no reward ever arrives and the weights never change. Live paper trading cannot bootstrap
itself out of that; a dataset of already-resolved trades can.

It is a WARM START, not a replacement for forward-test learning (§2/§15.8). It exists to get the
policy off random initialisation with a defensible prior, after which the real training signal
comes from live outcomes as it always has.

Why this file rather than reusing the old train.py: that one drove a Gymnasium replay env, which was
removed. There is no environment here. Every transition is already resolved — observation, action
taken, reward realised — so the buffer is filled directly and `train()` is called on it, which is
exactly what off-policy learning permits and what `learner.py` already does one trade at a time.

Usage:
    python -m rl_service.warmstart --data data/warmstart.jsonl --model models/sac_v8.zip
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from typing import Iterator

import numpy as np
from stable_baselines3 import SAC

from rl_service.obs import (
    ACTION_DIM,
    MAX_SLTP_OFFSET_PCT,
    OBSERVATION_SCHEMA_VERSION,
    Observation,
    mask_action_for_learning,
    to_vector,
)


@dataclass
class Sample:
    """One line of the dataset: a decision, its outcome, and what was actually done."""

    observation: Observation
    terminal: Observation
    reward: float
    # Diagnostics, carried so a rejected or surprising dataset can be inspected rather than guessed
    # at. Not model inputs.
    inst_id: str
    kind: str
    close_reason: str
    realized_pnl: float


def read_samples(path: str) -> Iterator[Sample]:
    """Streams the dataset, one sample per line.

    Streaming rather than loading the file: a run over months of history across every registered
    strategy produces hundreds of thousands of samples, and the buffer is the thing that must fit in
    memory, not the file that fills it.

    A malformed line is fatal rather than skipped. A dataset that silently trains on 90% of itself
    looks exactly like one that trains on all of it, and the difference only shows up as a policy
    that learned less than it should have — with nothing anywhere saying so.
    """
    with open(path, "r", encoding="utf-8") as f:
        for n, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                raw = json.loads(line)
                yield Sample(
                    observation=Observation.model_validate(raw["observation"]),
                    terminal=Observation.model_validate(raw["terminal"]),
                    reward=float(raw["reward"]),
                    inst_id=str(raw.get("inst_id", "")),
                    kind=str(raw.get("kind", "")),
                    close_reason=str(raw.get("close_reason", "")),
                    realized_pnl=float(raw.get("realized_pnl_usd", 0.0)),
                )
            except Exception as exc:  # noqa: BLE001 — the line number is what makes this useful
                raise ValueError(f"{path}:{n}: malformed sample: {exc}") from exc


def action_for(sample: Sample) -> np.ndarray:
    """Reconstructs the action vector for what the simulation ACTUALLY did.

    The dataset was produced without a model in the loop, so no policy chose these trades — every
    one was opened at the fixed slot size with the strategy's own levels. Off-policy learning is
    precisely what makes that usable: SAC learns from experience generated by ANY policy, so the
    requirement is not that a good policy produced the action, only that the action recorded is the
    one the reward belongs to.

    Getting this wrong is silent and total. An action vector that does not describe the trade the
    reward came from teaches the critic to value the wrong output, and nothing downstream can
    detect it — the numbers all remain well-formed.

    Layout is decode_action's, inverted (obs.py v5):
      [0] sl offset from last_price, scaled by MAX_SLTP_OFFSET_PCT
      [1] tp offset, same
      [2] size_pct as a fraction of the allowed budget
      [3] leverage_frac in [0, 1]
      [4] open head: >= 0 opens, < 0 skips
      [5:8] manage head — zeroed here, see below
    """
    obs = sample.observation
    vec = np.zeros(ACTION_DIM, dtype=np.float32)

    price = obs.last_price
    sig = obs.signal
    if price > 0 and sig is not None:
        if sig.sl_px > 0:
            vec[0] = np.clip((sig.sl_px / price - 1.0) / MAX_SLTP_OFFSET_PCT, -1.0, 1.0)
        if sig.tp_px > 0:
            vec[1] = np.clip((sig.tp_px / price - 1.0) / MAX_SLTP_OFFSET_PCT, -1.0, 1.0)

    # Size and leverage come from the TERMINAL observation, not the decision one. On a buy/sell
    # call position_state is zero-valued by design — the decision is whether to open at all, so
    # there is no position to describe yet. The terminal call is where the trade that was actually
    # taken is recorded, and that is the trade this reward belongs to.
    taken = sample.terminal.position_state

    # size_pct is read back as a fraction OF max_position_pct (decode_action scales it), so the
    # inverse divides by that budget. The budget is a fraction of equity, so the size must be too.
    equity = obs.account_equity_usd
    budget = obs.max_position_pct
    if equity > 0 and budget > 0:
        vec[2] = float(np.clip((taken.size_usd / equity) / budget, 0.0, 1.0))

    # leverage_frac maps [1x, max_leverage] onto [0, 1]. At max_leverage == 1 the range is a point
    # and every leverage is the same request, so 0.0 (the low end) rather than a division by zero.
    lev, cap = taken.leverage, obs.max_leverage
    if cap > 1.0 and lev > 0:
        vec[3] = float(np.clip((lev - 1.0) / (cap - 1.0), 0.0, 1.0))

    # The trade was taken, so the open head is positive.
    vec[4] = 1.0

    # The manage head decided nothing on a buy/sell call — decode_action discards it. Zeroing is
    # what stops reward reaching an output that had no effect; an output rewarded without causing
    # anything drifts to the tanh bound unopposed, which is the collapse §54.8 measured across all
    # nine outputs. mask_action_for_learning is the same function the live learner uses, so the two
    # paths cannot disagree about which head mattered.
    return mask_action_for_learning(vec, obs.category)


def main() -> None:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--data", required=True, help="warmstart.jsonl from cmd/backtest")
    p.add_argument("--model", required=True, help="the model to train, from rl_service.newmodel")
    p.add_argument("--out", default="", help="where to save (default: overwrite --model)")
    p.add_argument(
        "--gradient-steps",
        type=int,
        default=0,
        help="gradient steps to run (default: one per sample, a single pass over the data)",
    )
    p.add_argument("--batch-size", type=int, default=0, help="default: the model's own")
    p.add_argument("--limit", type=int, default=0, help="stop after N samples, for a smoke run")
    args = p.parse_args()

    model = SAC.load(args.model)

    # SB3 sets up its logger inside learn(), which this path never calls — it drives gradient steps
    # directly. Without one, train() raises on its first metric write. learner.py hit exactly this
    # and §15.11 records why it matters: there the error handler swallowed it and the service looked
    # healthy while never learning anything. Here it is fatal rather than silent, but attaching the
    # logger up front is the same fix, and keeps the two training paths behaving identically.
    if getattr(model, "_logger", None) is None:
        from stable_baselines3.common.logger import configure

        model.set_logger(configure(folder=None, format_strings=[]))

    want = int(model.observation_space.shape[0])
    print(f"model: obs_dim={want} act_dim={int(model.action_space.shape[0])}")
    print(f"schema: observation v{OBSERVATION_SCHEMA_VERSION}")

    if int(model.action_space.shape[0]) != ACTION_DIM:
        # A mismatched action width cannot be trained around: the buffer would hold vectors the
        # policy cannot emit. Refused loudly rather than reshaped, which is how §16.9's 83-vs-89
        # incident stayed invisible for a day.
        print(
            f"ERROR: model action width {int(model.action_space.shape[0])} != {ACTION_DIM}; "
            "rebuild it with rl_service.newmodel",
            file=sys.stderr,
        )
        raise SystemExit(1)

    n = 0
    rewards: list[float] = []
    for s in read_samples(args.data):
        # Already (1, DIM) and width-validated: v8's to_vector raises rather than padding, which
        # is what removed the truncation that let an 83-dim model serve an 89-dim pipeline with the
        # whole feature budget silently cut away (§16.9). The check below is on the model rather
        # than the data, which is the half to_vector cannot see.
        obs_vec = to_vector(s.observation)
        next_vec = to_vector(s.terminal)
        if obs_vec.shape[1] != want:
            print(
                f"ERROR: observation is {obs_vec.shape[1]} wide, model wants {want} — "
                "rebuild the model with rl_service.newmodel",
                file=sys.stderr,
            )
            raise SystemExit(1)

        model.replay_buffer.add(
            obs=obs_vec,
            next_obs=next_vec,
            action=action_for(s).reshape(1, -1),
            reward=np.array([s.reward], dtype=np.float32),
            # Terminal by construction: the trade is over, and bootstrapping a future value off the
            # closing observation would credit the policy for a position that no longer exists.
            done=np.array([True]),
            infos=[{}],
        )
        rewards.append(s.reward)
        n += 1
        if args.limit and n >= args.limit:
            break

    if n == 0:
        print("ERROR: dataset produced no samples", file=sys.stderr)
        raise SystemExit(1)

    arr = np.asarray(rewards, dtype=np.float64)
    print(f"loaded {n} samples into the replay buffer")
    print(
        f"reward: mean={arr.mean():+.4f} median={np.median(arr):+.4f} "
        f"min={arr.min():+.4f} max={arr.max():+.4f} positive={100.0 * (arr > 0).mean():.1f}%"
    )

    steps = args.gradient_steps or n
    batch = args.batch_size or model.batch_size
    print(f"training: {steps} gradient steps, batch {batch}")
    model.train(gradient_steps=steps, batch_size=batch)

    out = args.out or args.model
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    model.save(out)
    # Weights AND buffer, never weights alone: §15.11 is explicit that a model restored without its
    # experience comes back having forgotten everything it learned, which would throw away this
    # entire run the first time the service restarts.
    buf = f"{os.path.splitext(out)[0]}_buffer.pkl"
    model.save_replay_buffer(buf)
    print(f"saved {out} and {buf}")


if __name__ == "__main__":
    main()
