ALTER TABLE candles
    ALTER COLUMN open TYPE DOUBLE PRECISION,
    ALTER COLUMN high TYPE DOUBLE PRECISION,
    ALTER COLUMN low TYPE DOUBLE PRECISION,
    ALTER COLUMN close TYPE DOUBLE PRECISION,
    ALTER COLUMN volume TYPE DOUBLE PRECISION;

ALTER TABLE paper_orders
    ALTER COLUMN entry_px TYPE DOUBLE PRECISION,
    ALTER COLUMN sl_px TYPE DOUBLE PRECISION,
    ALTER COLUMN tp_px TYPE DOUBLE PRECISION,
    ALTER COLUMN size TYPE DOUBLE PRECISION,
    ALTER COLUMN leverage TYPE DOUBLE PRECISION,
    ALTER COLUMN close_px TYPE DOUBLE PRECISION,
    ALTER COLUMN realized_pnl TYPE DOUBLE PRECISION;
