ALTER TABLE candles
    ALTER COLUMN open TYPE NUMERIC,
    ALTER COLUMN high TYPE NUMERIC,
    ALTER COLUMN low TYPE NUMERIC,
    ALTER COLUMN close TYPE NUMERIC,
    ALTER COLUMN volume TYPE NUMERIC;

ALTER TABLE paper_orders
    ALTER COLUMN entry_px TYPE NUMERIC,
    ALTER COLUMN sl_px TYPE NUMERIC,
    ALTER COLUMN tp_px TYPE NUMERIC,
    ALTER COLUMN size TYPE NUMERIC,
    ALTER COLUMN leverage TYPE NUMERIC,
    ALTER COLUMN close_px TYPE NUMERIC,
    ALTER COLUMN realized_pnl TYPE NUMERIC;
